### ISSUE TITLE
Issue with usr/lib/python3.6/multiprocessing/synchronize.py

### ISSUE THREAD

**Issue by salmanjan11** [rockNroll87q/LOD-Brain#4]
While running the code, I'm facing a "FileNotFoundError: [Errno 2] No such file or directory. I checked in the directory the file exists, also tried different solutions on the internet but couldn't fix it. I have attached the screenshot as well.
<img width="954" alt="synchornize issue2" src="https://user-images.githubusercontent.com/28630552/230069150-f75b03e4-3c29-44d7-8af8-4628ac89bdc0.png">

<img width="709" alt="synchornize issue" src="https://user-images.githubusercontent.com/28630552/230068008-ac80f607-2d41-43cc-9a45-cd2f35e70764.png">

**Comment by salmanjan11** [comment]
There is some problem with wandb_init, I can not edit or open the file to fix this issue.

**Comment by rockNroll87q** [comment]
Dear @salmanjan11 , the problem seems to be related to wandb. The error could arise because you don't have permissions to initialise a run in the project specified (which it was our project).
I suggest to try this:

1. Visit [wandb](https://wandb.ai/site), create an account, and start a new project.
2. Change the code in [line 65](https://github.com/rockNroll87q/LOD-Brain/blob/main/src/main.py#L65) with the project name you have just started and try again. 

You may need to login in to wandb from terminal, but I'm not 100% sure.

**Comment by rockNroll87q** [comment]
Dear @salmanjan11 , I would suggest creating a new project, with a new name, and changing the project name in the code, not the opposite. Let me know

**Comment by salmanjan11** [comment]
Here is what I did. 
<img width="548" alt="wandb1" src="https://user-images.githubusercontent.com/28630552/231206039-f5af1f5d-e9bb-4574-9de2-590bbb092d7a.png">
<img width="893" alt="wandb2" src="https://user-images.githubusercontent.com/28630552/231206055-f5a89429-d069-4207-a7e0-c8dfc055599f.png">

**Comment by rockNroll87q** [comment]
Hi @salmanjan11 , did you try installing a new version of wandb inside and outside the container? Try to open a ipython console and simply import wandb and try to initiate. What does it give you in output?

**Comment by salmanjan11** [comment]
Yes, I have tried installing a new version of wandb both inside and outside the container. I will try to open an ipython consoles and check if the import and initialize works there.

**Comment by salmanjan11** [comment]
Tried re-installing Ubuntu and Singularity, which fixed the issue.
